### ISSUE TITLE
Can't libtbx configure on Windows

### ISSUE THREAD

**Issue by Anthchirp** [conda-forge/cctbx-base-feedstock#28]
running in an empty build directory next to the usual `modules/` checkouts with cctbx-base 2021.6 gives:

```
python ..\modules\cctbx_project\libtbx\configure.py scitbx iotbx cbflib

scitbx is already installed
Traceback (most recent call last):
  File "..\modules\cctbx_project\libtbx\configure.py", line 34, in <module>
    if not run():
  File "..\modules\cctbx_project\libtbx\configure.py", line 29, in run
    libtbx.env_config.cold_start(sys.argv)
  File "C:\DialsBuild\modules\cctbx_project\libtbx\env_config.py", line 3010, in cold_start
    env.process_args(pre_processed_args=pre_processed_args)
  File "C:\DialsBuild\modules\cctbx_project\libtbx\env_config.py", line 1046, in process_args
    assert self.path_utility.isfile()
AssertionError
```
a
`print(abs(self.path_utility))`
yields
`d:\bld\cctbx-base_1625205021395\_h_env\Lib\site-packages\command_line\path_utility.py`, 
so it looks like this comes from the prebuilt package?

**Comment by bkpoon** [comment]
I'll take a look this week. It looks like we're setting an absolute path which can happen on Windows.

**Comment by bkpoon** [comment]
There are some configuration issues on Windows that I'm looking into this week.

**Comment by bkpoon** [comment]
The Windows build should work now. It was not working in earlier releases since it was not fully tested.

1) Create the environment with one of the recent nightly builds of the `cctbx-base` package. The only package in the environment that comes from the `cctbx-nightly` channel is `cctbx-base`. Everything else should come from `conda-forge`.
```
conda create -n test -c cctbx-nightly -c conda-forge cctbx-base python=3.7 scons hdf5=1.10
conda activate test
```
2) Configure (`dxtbx` is on the `dials-3.5` branch)
```
mkdir build
cd build
libtbx.configure dxtbx cbflib
```
3) Build (the Visual C++ 2017 compiler is already in the path)
```
libtbx.scons -j 8
```
